### ISSUE TITLE
Develop branch

### ISSUE THREAD

**Issue by RickCogley** [autonomy/alterant#2]
Hi Andrew, thanks for your answer in: https://github.com/andrewrynhard/dotfiles/issues/1

I'm indeed interested in learning how to use the ``develop`` branch and appreciate your help. The one thing I like about ``alterant`` above ``homemaker`` is you're just using standard bash scripts in yaml. That's a bit easier to grok compared "to" "the" "somewhat" "odd" "style" "of" "entering" "commands" seen in homemaker. 😄 Yaml can be fiddly, though. 

The challenge you mention about needing to edit the config files in a separately cloned copy of your dotfiles, pushing, then re-running ``alterant`` sounds like a pain. Why's it like that? Is that something that's easily fixable? 

I already have pgp keys; can I just link them into ``~/.alterant`` ?

Also, how can we handle a situation where, say I use ``brew`` to install an app, and it creates skeleton ``.rc`` files in ``~``. Will ``alterant`` overwrite/override those?

Appreciate your consideration, 
thanks
Rick

**Comment by andrewrynhard** [comment]
Hell Rick. Thank you for opening the issue. So the problem of having to clone the repo, push it, then use alterant to pull it again is because currently alterant uses git2go and the way that the branch is checked out leaves it unattached. This is definitely easily fixable, I just need to understand git2go/libgit2 a little more to fix it. Feel free to take a stab at it if you have any experience with these. The relevant function can be found [here](https://github.com/autonomy/alterant/blob/develop/repo/repo.go#L207-L237). As for the PGP keys you can give it a try. This only fixes half the problem unfortunately. The other problem is that The current state of the `develop` branch was left in a state when I was working on supporting cloning of the repo without the need for git. The idea was that on a fresh install, I would love to just be able to download alterant and use it to install the dotfiles, and then perform some lightweight provisioning with the commands it can run and install hombres, git, etc... So to fix this a way of determining whether to use the locally cloned repo or the remote repo (currently the only option) will be used as the source. I haven't settled on whether a flag like `--local` should be provided or a simple check of the number of arguments. Two for the remote branch (URL and branch name) and one for local (the location). Your opinion is welcome.

Again, the OpenPGP package is something I could understand better as well. Here is the output from alterant's help:

````
$ alterant --help
NAME:
   alterant - Alter your machine with ease.

USAGE:
   alterant [global options] command [command options] [arguments...]
   
VERSION:
   0.2.1
   
COMMANDS:
   provision	provision a machine
   remove	remove provisioned tasks
   new		create a new machine
   open		open an existing machine
   list		list available machines
   encrypt	encrypt files
   decrypt	decrypt files
   gen-key	generate a private/public key pair
   help, h	Shows a list of commands or help for one command
   
GLOBAL OPTIONS:
   --password 							password to encrypt/decrypt a file
   --private "/Users/andrewrynhard/.alterant/secring.gpg"	openpgp ASCII armored private key
   --public "/Users/andrewrynhard/.alterant/pubring.gpg"	openpgp ASCII armored public key
   --verbose							use verbose logging
   --help, -h							show help
   --version, -v						print the version
````
As you can see, the public and private keys can be specified with `--public` and `--private` respectively. This SHOULD work however I haven't tested it.

Now, to answer your final question, alterant will only overwrite files if you provide `--clobber=true` to the list of options for the `provision` command. If you specify that one of the files in your dotfiles repo should be linked to the same location as one of the skeleton files, then this flag will remove the rc file and link the file you have specified in the yaml. Here is the help menu for the `provision` command. 

````
$ alterant provision --help
NAME:
   alterant provision - provision a machine

USAGE:
   alterant provision [command options] [arguments...]

OPTIONS:
   --links	provision links, defaults to true
   --commands	provision commands, defaults to true
   --parents	make parent directories as needed, defaults to false
   --clobber	remove existing files/directories before linking, defaults to false
````

Finally here is an example:
````
$ alterant provision https://github.com/andrewrynhard/dotfiles.git macbookpro
````
This will clone the `macbookpro` branch of `https://github.com/andrewrynhard/dotfiles.git` to `~/.alterant` and execute a yaml named after the branch `macbookpro.yaml`. Please let me know if I have missed anything.

**Comment by andrewrynhard** [comment]
@RickCogley This issue has motivated me to fix a few things. I will be pushing (hopefully very shortly) a new version that eliminates the need for installing libssh2, and removes the inconvenience of having a detached HEAD when cloning the dotfile repo. Now when `alterant` clones the repo you can edit and push without having to do the messy workaround that I mentioned. The binary will also have libssh2 statically linked so you can use it on a fresh install without any prerequisites.

**Comment by RickCogley** [comment]
Thanks Andrew. 

> On Apr 16, 2016, at 2:55 PM, Andrew Rynhard <notifications@github.com> wrote:
> 
> @RickCogley <https://github.com/RickCogley> This issue has motivated me to fix a few things. I will be pushing (hopefully very shortly) a new version that eliminates the need for installing libssh2, and removes the inconvenience of having a detached HEAD when cloning the dotfile repo. Now when alterant clones the repo you can edit and push without having to do the messy workaround that I mentioned. The binary will also have libssh2 statically linked so you can use it on a fresh install without any prerequisites.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/autonomy/alterant/issues/2#issuecomment-210741909>


-- 
*This email message and any attachments are confidential, and are meant to 
be read by the intended recipient only. If you are not the intended 
recipient, we would request you delete this message or any attachments 
without reading or distributing, and kindly advise eSolia Inc. (contacts: 
esolia.com/about <http://esolia.com/about>). Thank you in advance.*

**Comment by andrewrynhard** [comment]
@RickCogley closing this. See https://github.com/autonomy/alterant/releases/tag/v0.2.2-alpha
